"""Decide which changed files are worth an LLM's attention.

Every skipped file gets a reason, which ends up in the review summary and the
dashboard, so "why didn't it review X?" always has an answer.
"""

import re
from collections.abc import Iterable, Sequence
from functools import lru_cache

from app.review.models import FileDiff, SkippedFile

DEFAULT_IGNORE_PATTERNS: tuple[str, ...] = (
    # lockfiles
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "uv.lock",
    "Cargo.lock",
    "composer.lock",
    "Gemfile.lock",
    "go.sum",
    # build output and vendored code
    "dist/**",
    "build/**",
    "vendor/**",
    "node_modules/**",
    "*.min.js",
    "*.min.css",
    "*.map",
    "*.snap",
    # binaries, media, fonts
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.webp",
    "*.ico",
    "*.pdf",
    "*.zip",
    "*.gz",
    "*.woff",
    "*.woff2",
    "*.ttf",
    "*.otf",
    "*.eot",
    "*.mp4",
    "*.mp3",
    "*.exe",
    "*.dll",
    "*.so",
    "*.dylib",
    "*.jar",
    "*.pyc",
)
GENERATED_MARKERS = ("@generated", "do not edit", "code generated by", "auto-generated")
GENERATED_SCAN_LINES = 10


def filter_files(
    files: Sequence[FileDiff], extra_ignore_patterns: Iterable[str] = ()
) -> tuple[list[FileDiff], list[SkippedFile]]:
    patterns = (*DEFAULT_IGNORE_PATTERNS, *extra_ignore_patterns)
    kept: list[FileDiff] = []
    skipped: list[SkippedFile] = []
    for file in files:
        reason = _skip_reason(file, patterns)
        if reason:
            skipped.append(SkippedFile(file.path, reason))
        else:
            kept.append(file)
    return kept, skipped


def _skip_reason(file: FileDiff, patterns: Sequence[str]) -> str | None:
    if file.status == "removed":
        return "deleted"
    if file.is_binary:
        return "binary"
    if file.patch_missing:
        return "diff_too_large"  # GitHub didn't send a patch
    if any(path_matches(file.path, pattern) for pattern in patterns):
        return "ignored_path"
    if file.additions == 0:
        return "no_added_lines"
    if _looks_generated(file):
        return "generated"
    return None


def _looks_generated(file: FileDiff) -> bool:
    # Only new files reliably show their header in the diff.
    if file.status != "added" or not file.hunks:
        return False
    head = [line.content.lower() for line in file.hunks[0].lines[:GENERATED_SCAN_LINES]]
    return any(marker in line for line in head for marker in GENERATED_MARKERS)


def path_matches(path: str, pattern: str) -> bool:
    """gitignore-flavoured glob matching.

    - `*` matches within one path segment, `**` across segments.
    - A pattern without "/" matches the file name in any directory
      ("*.min.js" matches "web/static/app.min.js").
    """
    pattern = pattern.strip().lstrip("/")
    if not pattern:
        return False
    if "/" not in pattern:
        return _compile(pattern).fullmatch(path.rsplit("/", 1)[-1]) is not None
    return _compile(pattern).fullmatch(path) is not None


@lru_cache(maxsize=512)
def _compile(pattern: str) -> re.Pattern[str]:
    regex = ""
    index = 0
    while index < len(pattern):
        if pattern.startswith("**/", index):
            regex += "(?:.*/)?"
            index += 3
        elif pattern.startswith("**", index):
            regex += ".*"
            index += 2
        elif pattern[index] == "*":
            regex += "[^/]*"
            index += 1
        elif pattern[index] == "?":
            regex += "[^/]"
            index += 1
        else:
            regex += re.escape(pattern[index])
            index += 1
    return re.compile(regex)
