/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Github Webhook */
        post: operations["github_webhook_api_v1_webhooks_github_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/github/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login_api_v1_auth_github_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_api_v1_auth_github_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/installations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Installations */
        get: operations["list_installations_api_v1_installations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/installations/{installation_id}/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Repositories */
        get: operations["list_repositories_api_v1_installations__installation_id__repositories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Repositories */
        get: operations["list_all_repositories_api_v1_repositories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Repository */
        patch: operations["update_repository_api_v1_repositories__repository_id__patch"];
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Repository Config */
        get: operations["repository_config_api_v1_repositories__repository_id__config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/pulls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pulls */
        get: operations["list_pulls_api_v1_repositories__repository_id__pulls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pulls/{pull_request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pull */
        get: operations["get_pull_api_v1_pulls__pull_request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pulls/{pull_request_id}/rereview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rereview */
        post: operations["rereview_api_v1_pulls__pull_request_id__rereview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analytics Overview */
        get: operations["analytics_overview_api_v1_analytics_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyticsOverview */
        AnalyticsOverview: {
            /** Range Days */
            range_days: number;
            /** Runs Total */
            runs_total: number;
            /** Runs Completed */
            runs_completed: number;
            /** Runs Failed */
            runs_failed: number;
            /** Comments Posted */
            comments_posted: number;
            /** Cost Usd Total */
            cost_usd_total: number;
            /** Usd To Inr */
            usd_to_inr: number | null;
            /** Avg Latency Ms */
            avg_latency_ms: number | null;
            /** P95 Latency Ms */
            p95_latency_ms: number | null;
            feedback: components["schemas"]["RateOut"];
            /** Feedback By Category */
            feedback_by_category: {
                [key: string]: components["schemas"]["RateOut"];
            };
            /** Feedback By Severity */
            feedback_by_severity: {
                [key: string]: components["schemas"]["RateOut"];
            };
            /** Reviews Per Day */
            reviews_per_day: components["schemas"]["DayCount"][];
            /** Cost Per Day */
            cost_per_day: components["schemas"]["DayCost"][];
            /** Comments By Severity */
            comments_by_severity: {
                [key: string]: number;
            };
            /** Comments By Category */
            comments_by_category: {
                [key: string]: number;
            };
            /** Top Files */
            top_files: components["schemas"]["FileCount"][];
        };
        /** CommentOut */
        CommentOut: {
            /** Id */
            id: number;
            /** Path */
            path: string;
            /** Line */
            line: number;
            /** Start Line */
            start_line: number | null;
            /** Severity */
            severity: string;
            /** Category */
            category: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Suggestion */
            suggestion: string | null;
            /** Confidence */
            confidence: number | null;
            /** Source */
            source: string;
            /** Posted */
            posted: boolean;
            /** Drop Reason */
            drop_reason: string | null;
            /** Status */
            status: string;
            /** Thumbs Up */
            thumbs_up: number;
            /** Thumbs Down */
            thumbs_down: number;
            /** Github Url */
            github_url: string | null;
        };
        /** DayCost */
        DayCost: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Cost Usd */
            cost_usd: number;
        };
        /** DayCount */
        DayCount: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Count */
            count: number;
        };
        /** FileCount */
        FileCount: {
            /** Repository Full Name */
            repository_full_name: string;
            /** Path */
            path: string;
            /** Count */
            count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InstallationOut */
        InstallationOut: {
            /** Id */
            id: number;
            /** Github Installation Id */
            github_installation_id: number;
            /** Account Login */
            account_login: string;
            /** Account Type */
            account_type: string;
            /** Suspended */
            suspended: boolean;
            /** Repositories Count */
            repositories_count: number;
        };
        /** InstallationsResponse */
        InstallationsResponse: {
            /** Installations */
            installations: components["schemas"]["InstallationOut"][];
            /** Install Url */
            install_url: string;
        };
        /** LLMCallOut */
        LLMCallOut: {
            /** Id */
            id: number;
            /** Purpose */
            purpose: string;
            /** Model */
            model: string;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cost Usd */
            cost_usd: number;
            /** Latency Ms */
            latency_ms: number;
            /** Status */
            status: string;
            /** Error */
            error: string | null;
        };
        /** MeResponse */
        MeResponse: {
            /** Id */
            id: number;
            /** Login */
            login: string;
            /** Avatar Url */
            avatar_url: string | null;
        };
        /** Page[PullOut] */
        Page_PullOut_: {
            /** Items */
            items: components["schemas"]["PullOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** PullDetailOut */
        PullDetailOut: {
            /** Id */
            id: number;
            /** Repository Id */
            repository_id: number;
            /** Repository Full Name */
            repository_full_name: string;
            /** Number */
            number: number;
            /** Title */
            title: string;
            /** Author Login */
            author_login: string;
            /** State */
            state: string;
            /** Draft */
            draft: boolean;
            /** Paused */
            paused: boolean;
            /** Head Sha */
            head_sha: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Html Url */
            html_url: string;
            last_run: components["schemas"]["RunSummaryOut"] | null;
            /** Runs */
            runs: components["schemas"]["RunSummaryOut"][];
        };
        /** PullOut */
        PullOut: {
            /** Id */
            id: number;
            /** Repository Id */
            repository_id: number;
            /** Repository Full Name */
            repository_full_name: string;
            /** Number */
            number: number;
            /** Title */
            title: string;
            /** Author Login */
            author_login: string;
            /** State */
            state: string;
            /** Draft */
            draft: boolean;
            /** Paused */
            paused: boolean;
            /** Head Sha */
            head_sha: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Html Url */
            html_url: string;
            last_run: components["schemas"]["RunSummaryOut"] | null;
        };
        /** RateOut */
        RateOut: {
            /** Posted */
            posted: number;
            /** Helpful */
            helpful: number;
            /** Negative */
            negative: number;
            /** Helpful Rate */
            helpful_rate: number | null;
            /** Negative Rate */
            negative_rate: number | null;
        };
        /** RepositoryConfigOut */
        RepositoryConfigOut: {
            /** Commit Sha */
            commit_sha: string;
            /** Is Valid */
            is_valid: boolean;
            /** Has File */
            has_file: boolean;
            /** Raw Yaml */
            raw_yaml: string | null;
            /** Parsed */
            parsed: {
                [key: string]: unknown;
            };
            /** Errors */
            errors: string[];
            /** Warnings */
            warnings: string[];
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
        };
        /** RepositoryOut */
        RepositoryOut: {
            /** Id */
            id: number;
            /** Installation Id */
            installation_id: number;
            /** Full Name */
            full_name: string;
            /** Private */
            private: boolean;
            /** Enabled */
            enabled: boolean;
            /** Default Branch */
            default_branch: string | null;
            /** Last Reviewed At */
            last_reviewed_at: string | null;
            /**
             * Config Status
             * @enum {string}
             */
            config_status: "valid" | "invalid" | "none" | "unknown";
            /** Open Pulls */
            open_pulls: number;
        };
        /** RepositoryUpdate */
        RepositoryUpdate: {
            /** Enabled */
            enabled: boolean;
        };
        /** RereviewResponse */
        RereviewResponse: {
            /** Run Id */
            run_id: number;
        };
        /** RunDetailOut */
        RunDetailOut: {
            /** Id */
            id: number;
            /** Trigger */
            trigger: string;
            /** Mode */
            mode: string;
            /** Status */
            status: string;
            /** Skip Reason */
            skip_reason: string | null;
            /** Head Sha */
            head_sha: string;
            /** Files Reviewed */
            files_reviewed: number;
            /** Comments Posted */
            comments_posted: number;
            /** Cost Usd */
            cost_usd: number;
            /** Latency Ms */
            latency_ms: number | null;
            /** Error Code */
            error_code: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Pull Request Id */
            pull_request_id: number;
            /** Pull Request Number */
            pull_request_number: number;
            /** Pull Request Title */
            pull_request_title: string;
            /** Repository Full Name */
            repository_full_name: string;
            /** Base Sha */
            base_sha: string;
            /** From Sha */
            from_sha: string | null;
            /** Mode Reason */
            mode_reason: string | null;
            /** Prompt Version */
            prompt_version: string | null;
            /** Model */
            model: string | null;
            /** Files Total */
            files_total: number;
            /** Files Skipped */
            files_skipped: components["schemas"]["SkippedFileOut"][];
            /** Comments Generated */
            comments_generated: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Error Message */
            error_message: string | null;
            /** Summary */
            summary: {
                [key: string]: unknown;
            } | null;
            /** Github Review Url */
            github_review_url: string | null;
            /** Started At */
            started_at: string | null;
            /** Llm Calls */
            llm_calls: components["schemas"]["LLMCallOut"][];
            /** Comments */
            comments: components["schemas"]["CommentOut"][];
        };
        /** RunSummaryOut */
        RunSummaryOut: {
            /** Id */
            id: number;
            /** Trigger */
            trigger: string;
            /** Mode */
            mode: string;
            /** Status */
            status: string;
            /** Skip Reason */
            skip_reason: string | null;
            /** Head Sha */
            head_sha: string;
            /** Files Reviewed */
            files_reviewed: number;
            /** Comments Posted */
            comments_posted: number;
            /** Cost Usd */
            cost_usd: number;
            /** Latency Ms */
            latency_ms: number | null;
            /** Error Code */
            error_code: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
        };
        /** SkippedFileOut */
        SkippedFileOut: {
            /** Path */
            path: string;
            /** Reason */
            reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    github_webhook_api_v1_webhooks_github_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_v1_auth_github_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    callback_api_v1_auth_github_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_installations_api_v1_installations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallationsResponse"];
                };
            };
        };
    };
    list_repositories_api_v1_installations__installation_id__repositories_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                installation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_repositories_api_v1_repositories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryOut"][];
                };
            };
        };
    };
    update_repository_api_v1_repositories__repository_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repository_config_api_v1_repositories__repository_id__config_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryConfigOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pulls_api_v1_repositories__repository_id__pulls_get: {
        parameters: {
            query?: {
                state?: ("open" | "closed" | "merged") | null;
                /** @description next_cursor from the previous page */
                cursor?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PullOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pull_api_v1_pulls__pull_request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pull_request_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PullDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rereview_api_v1_pulls__pull_request_id__rereview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pull_request_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RereviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analytics_overview_api_v1_analytics_overview_get: {
        parameters: {
            query?: {
                range?: "7d" | "30d" | "90d";
                repository_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
