"""installations repositories pull requests webhook deliveries

Revision ID: e2deb8334440
Revises: 
Create Date: 2026-09-24 16:44:11.974855
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'e2deb8334440'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installations',
    sa.Column('github_installation_id', sa.BigInteger(), nullable=False),
    sa.Column('account_login', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=32), nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installations')),
    sa.UniqueConstraint('github_installation_id', name=op.f('uq_installations_github_installation_id'))
    )
    op.create_table('webhook_deliveries',
    sa.Column('delivery_id', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('installation_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ignore_reason', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('delivery_id', name=op.f('pk_webhook_deliveries'))
    )
    op.create_index(op.f('ix_webhook_deliveries_received_at'), 'webhook_deliveries', ['received_at'], unique=False)
    op.create_table('repositories',
    sa.Column('installation_id', sa.BigInteger(), nullable=False),
    sa.Column('github_repo_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], name=op.f('fk_repositories_installation_id_installations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repositories')),
    sa.UniqueConstraint('github_repo_id', name=op.f('uq_repositories_github_repo_id'))
    )
    op.create_index(op.f('ix_repositories_installation_id'), 'repositories', ['installation_id'], unique=False)
    op.create_table('pull_requests',
    sa.Column('repository_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('github_pr_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('author_login', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('draft', sa.Boolean(), nullable=False),
    sa.Column('base_ref', sa.String(length=255), nullable=False),
    sa.Column('base_sha', sa.String(length=40), nullable=False),
    sa.Column('head_sha', sa.String(length=40), nullable=False),
    sa.Column('last_reviewed_sha', sa.String(length=40), nullable=True),
    sa.Column('paused', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_pull_requests_repository_id_repositories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pull_requests'))
    )
    op.create_index('ix_pull_requests_repository_id_state', 'pull_requests', ['repository_id', 'state'], unique=False)
    op.create_index('uq_pull_requests_repository_id_number', 'pull_requests', ['repository_id', 'number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_pull_requests_repository_id_number', table_name='pull_requests')
    op.drop_index('ix_pull_requests_repository_id_state', table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_index(op.f('ix_repositories_installation_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_webhook_deliveries_received_at'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_table('installations')
    # ### end Alembic commands ###
