"""run summary and mode reason

Revision ID: df546033512c
Revises: ac148df4501c
Create Date: 2026-09-25 16:59:16.590744
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'df546033512c'
down_revision: str | None = 'ac148df4501c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_runs', sa.Column('mode_reason', sa.String(length=64), nullable=True))
    op.add_column('review_runs', sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_runs', 'summary')
    op.drop_column('review_runs', 'mode_reason')
    # ### end Alembic commands ###
