"""review runs llm calls comments repo configs

Revision ID: ac148df4501c
Revises: e2deb8334440
Create Date: 2026-09-25 15:54:35.886868
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ac148df4501c'
down_revision: str | None = 'e2deb8334440'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_configs',
    sa.Column('repository_id', sa.BigInteger(), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('raw_yaml', sa.Text(), nullable=True),
    sa.Column('parsed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_repo_configs_repository_id_repositories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repo_configs'))
    )
    op.create_index('uq_repo_configs_repository_id_commit_sha', 'repo_configs', ['repository_id', 'commit_sha'], unique=True)
    op.create_table('review_runs',
    sa.Column('pull_request_id', sa.BigInteger(), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('base_sha', sa.String(length=40), nullable=False),
    sa.Column('head_sha', sa.String(length=40), nullable=False),
    sa.Column('from_sha', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('skip_reason', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=16), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('files_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('files_reviewed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('files_skipped', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('comments_generated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comments_posted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comments_dropped_invalid_line', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comments_dropped_duplicate', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comments_dropped_low_confidence', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comments_dropped_over_limit', sa.Integer(), server_default='0', nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('github_review_id', sa.BigInteger(), nullable=True),
    sa.Column('check_run_id', sa.BigInteger(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], name=op.f('fk_review_runs_pull_request_id_pull_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_runs'))
    )
    op.create_index('ix_review_runs_pull_request_id_created_at', 'review_runs', ['pull_request_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_review_runs_status_started_at', 'review_runs', ['status', 'started_at'], unique=False)
    op.create_table('llm_calls',
    sa.Column('review_run_id', sa.BigInteger(), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], name=op.f('fk_llm_calls_review_run_id_review_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls'))
    )
    op.create_index(op.f('ix_llm_calls_review_run_id'), 'llm_calls', ['review_run_id'], unique=False)
    op.create_table('review_comments',
    sa.Column('review_run_id', sa.BigInteger(), nullable=False),
    sa.Column('pull_request_id', sa.BigInteger(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(length=8), server_default='RIGHT', nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), server_default='llm', nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('code_snapshot', sa.Text(), nullable=True),
    sa.Column('posted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('drop_reason', sa.String(length=64), nullable=True),
    sa.Column('github_comment_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('thumbs_up', sa.Integer(), server_default='0', nullable=False),
    sa.Column('thumbs_down', sa.Integer(), server_default='0', nullable=False),
    sa.Column('feedback_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], name=op.f('fk_review_comments_pull_request_id_pull_requests')),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], name=op.f('fk_review_comments_review_run_id_review_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_comments'))
    )
    op.create_index('ix_review_comments_pull_request_id', 'review_comments', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_review_comments_review_run_id'), 'review_comments', ['review_run_id'], unique=False)
    op.create_index('ix_review_comments_status_feedback_checked_at', 'review_comments', ['status', 'feedback_checked_at'], unique=False)
    op.create_index('uq_review_comments_pull_request_id_fingerprint_posted', 'review_comments', ['pull_request_id', 'fingerprint'], unique=True, postgresql_where=sa.text('posted'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_review_comments_pull_request_id_fingerprint_posted', table_name='review_comments', postgresql_where=sa.text('posted'))
    op.drop_index('ix_review_comments_status_feedback_checked_at', table_name='review_comments')
    op.drop_index(op.f('ix_review_comments_review_run_id'), table_name='review_comments')
    op.drop_index('ix_review_comments_pull_request_id', table_name='review_comments')
    op.drop_table('review_comments')
    op.drop_index(op.f('ix_llm_calls_review_run_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index('ix_review_runs_status_started_at', table_name='review_runs')
    op.drop_index('ix_review_runs_pull_request_id_created_at', table_name='review_runs')
    op.drop_table('review_runs')
    op.drop_index('uq_repo_configs_repository_id_commit_sha', table_name='repo_configs')
    op.drop_table('repo_configs')
    # ### end Alembic commands ###
