import pytest

from app.review.diff_parser import parse_patch
from app.review.filters import filter_files, path_matches
from app.review.models import FileDiff


def _file(path: str, patch: str | None = "@@ -0,0 +1 @@\n+x = 1", **kwargs: object) -> FileDiff:
    return parse_patch(path, patch, **kwargs)  # type: ignore[arg-type]


@pytest.mark.parametrize(
    ("path", "pattern", "expected"),
    [
        ("web/static/app.min.js", "*.min.js", True),  # no "/" → matches the basename anywhere
        ("app.min.js", "*.min.js", True),
        ("dist/bundle.js", "dist/**", True),
        ("dist/a/b/c.js", "dist/**", True),
        ("src/dist/x.js", "dist/**", False),  # anchored at the repo root
        ("docs/guide.md", "docs/**", True),
        ("api.generated.ts", "**/*.generated.ts", True),  # "**/" also matches zero dirs
        ("src/api/x.generated.ts", "**/*.generated.ts", True),
        ("src/api.ts", "**/*.generated.ts", False),
        ("src/a.py", "src/*.py", True),
        ("src/pkg/a.py", "src/*.py", False),  # "*" doesn't cross "/"
    ],
)
def test_path_matches(path: str, pattern: str, expected: bool) -> None:
    assert path_matches(path, pattern) is expected


def test_skip_reasons() -> None:
    files = [
        _file("app/main.py"),
        _file("package-lock.json"),
        _file("web/app.min.js"),
        _file("old.py", "@@ -1 +0,0 @@\n-x = 1", status="removed"),
        _file("big.py", None),
        _file("docs/readme.md"),
        _file("only_deletes.py", "@@ -1,2 +1,1 @@\n a\n-b"),
        _file("gen/models.py", "@@ -0,0 +1,2 @@\n+# @generated by protoc\n+x = 1", status="added"),
    ]
    kept, skipped = filter_files(files, extra_ignore_patterns=["docs/**"])

    assert [file.path for file in kept] == ["app/main.py"]
    assert {s.path: s.reason for s in skipped} == {
        "package-lock.json": "ignored_path",
        "web/app.min.js": "ignored_path",
        "old.py": "deleted",
        "big.py": "diff_too_large",
        "docs/readme.md": "ignored_path",
        "only_deletes.py": "no_added_lines",
        "gen/models.py": "generated",
    }
